title: "[Q&A] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: "Ask a question about ELO-AGI, cognitive modules, or the architecture."
  - type: textarea
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Context
      description: Any relevant context (version, OS, what you've tried)
